pipelines:
  tags:
    'release-*':
      - parallel:
        - step:
            name: Building for Windows (x86_64)
            image: registry.fedoraproject.org/fedora-minimal:32
            script:
              - microdnf install glib2-devel gtk3-devel cairo-devel pango-devel meson ninja-build libappstream-glib desktop-file-utils gcc mingw64-gcc mingw64-pango mingw64-poppler mingw64-gtk3 mingw64-winpthreads mingw64-winpthreads-static
              - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rust-init.sh
              - bash rust-init.sh -y --profile minimal -t x86_64-pc-windows-gnu,x86_64-unknown-linux-gnu
              - rm rust-init.sh
              - source $HOME/.cargo/env
              - meson -Dbuildtype=release windows
              - cd windows
              - BLACKBODY_BUILDER=windows ninja
              - cp /usr/x86_64-w64-mingw32/sys-root/mingw/bin/*.dll src/
              - cp /usr/x86_64-w64-mingw32/sys-root/mingw/bin/gdbus.exe src/
              - mkdir -p src/share/glib-2.0/schemas
              - cp /usr/x86_64-w64-mingw32/sys-root/mingw/share/glib-2.0/schemas/gschemas.compiled src/share/glib-2.0/schemas/gschemas.compiled
              - cp -r /usr/x86_64-w64-mingw32/sys-root/mingw/share/icons src/share/icons
              - mkdir dist
              - export VERSION=`echo $BITBUCKET_TAG | sed -e 's,release-,,'`
              - mv src dist/blackbody-$VERSION-windows
              - cd dist
              - zip -r blackbody-$VERSION-windows.zip blackbody-$VERSION-windows
            artifacts:
              - windows/dist/*.zip
        - step:
            name: Packaging for Linux (src)
            script:
              - export VERSION=`echo $BITBUCKET_TAG | sed -e 's,release-,,'`
              - mkdir -p source/dist
              - ls -l source/dist
              - git archive master | bzip2 > blackbody-$VERSION-source.tar.bz2
              - mv blackbody-$VERSION-source.tar.bz2 source/dist/
              - ls -l source/dist
            artifacts:
              - source/dist/*.tar.bz2
      - parallel:
        - step:
            name: Publishing to downloads page
            clone:
              enabled: false
            script:
              - export VERSION=`echo $BITBUCKET_TAG | sed -e 's,release-,,'`
              - export WIN_PACKAGE=windows/dist/blackbody-$VERSION-windows.zip
              - export SRC_PACKAGE=source/dist/blackbody-$VERSION-source.tar.bz2
              - ls $WIN_PACKAGE $SRC_PACKAGE
              - curl -X POST --user "$BLACKBODY_CI_BB_UN:$BLACKBODY_CI_BB_PW" "https://api.bitbucket.org/2.0/repositories/$BITBUCKET_REPO_OWNER/$BITBUCKET_REPO_SLUG/downloads" --form files=@"$WIN_PACKAGE"
              - curl -X POST --user "$BLACKBODY_CI_BB_UN:$BLACKBODY_CI_BB_PW" "https://api.bitbucket.org/2.0/repositories/$BITBUCKET_REPO_OWNER/$BITBUCKET_REPO_SLUG/downloads" --form files=@"$SRC_PACKAGE"
        - step:
            name: Publishing to Flathub
            script:
              - git clone git@github.com:flathub/eu.nimmerfort.blackbody.git
              - cd eu.nimmerfort.blackbody
              - export $BRANCH=test/$BITBUCKET_TAG-$BITBUCKET_COMMIT
              - git checkout -b $BRANCH
              - python3 ../build-aux/flathub/flatpak-cargo-generator.py -o Cargo-sources.json ../Cargo.lock
              - jq ".modules[0].sources[1].tag = \"$BITBUCKET_TAG\" | .modules[0].sources[1].commit = \"BITBUCKET_COMMIT\"" ../eu.nimmerfort.blackbody-flathub.json > eu.nimmerfort.blackbody.json
              - git add Cargo-sources.json eu.nimmerfort.blackbody.json
              - git commit -m $BITBUCKET_TAG
              - git push --set-upstream $BRANCH
              - git push

    test-*:
      - step:
          name: Publishing to Flathub
          # image: python:3.8-slim
          image: atlassian/default-image:3
          script:
            # - apt-get update && apt-get install -y git
            # Set up environment
            - pip install toml
            - export BRANCH=test/$BITBUCKET_TAG-$BITBUCKET_COMMIT
            - git clone git@github.com:flathub/eu.nimmerfort.blackbody.git
            - cd eu.nimmerfort.blackbody
            - git checkout -b $BRANCH
            # Generate updates
            - python3 ../build-aux/flathub/flatpak-cargo-generator.py -o Cargo-sources.json ../Cargo.lock
            - jq ".modules[0].sources[1].tag = \"$BITBUCKET_TAG\" | .modules[0].sources[1].commit = \"BITBUCKET_COMMIT\"" ../eu.nimmerfort.blackbody-flathub.json > eu.nimmerfort.blackbody.json
            # Commit and push
            - git add Cargo-sources.json eu.nimmerfort.blackbody.json
            - git commit -m $BITBUCKET_TAG
            - git push --set-upstream $BRANCH
            - git push


      # - step:
      #   name: Publishing to Flathub repository
      #   script:
          # TODO
      #     - echo "Done"
