[[bin]]
name = "blackbody"
path = "src/main.rs"

[dependencies]
ndarray = "0.15.4"
tiff = "0.6.0"
flyr = "0.5.0" 
rexif = "0.7.3"

[dependencies.cairo-rs]
version = "0.14.0"

[dependencies.gdk]
version = "0.14.0"

[dependencies.gdk-pixbuf]
version = "0.14.0"

[dependencies.gettext-rs]
version = "0.4.4"
features = [ "gettext-system",]

[dependencies.gio]
version = "0.14.0"

[dependencies.glib]
version = "0.14.0"

[dependencies.gtk]
version = "0.14.0"
features = [ "v3_24",]

[dependencies.image]
version = "0.23.14"
default-features = false
features = ["png"]

[lib]
name = "libblackbody"
path = "src/lib/lib.rs"

[package]
name = "blackbody"
description = "Blackbody is an image viewer for thermograms."
version = "2.0.0"
license = "EUPL-1.2"
authors = [ "Arthur Nieuwland <anieuwland@nimmerfort.eu>",]
edition = "2018"
repository = "https://bitbucket.org/nimmerwoner/blackbody/"
