[[bin]]
name = "blackbody"
path = "src/main.rs"

[dependencies]
ndarray = "0.17"
tiff = "0.6.0"
flyr = "0.7.0"

[dependencies.cairo-rs]
version = "0.22"

[dependencies.gdk-pixbuf]
version = "0.22"

[dependencies.gettext-rs]
version = "0.7"
features = [ "gettext-system",]

[dependencies.gio]
version = "0.22"

[dependencies.glib]
version = "0.22"

[dependencies.gtk4]
version = "0.11"
features = [ "v4_12",]

[dependencies.libadwaita]
version = "0.9"
features = [ "v1_7",]

[dependencies.image]
version = "0.23.14"
default-features = false
features = ["png"]

[lib]
name = "libblackbody"
path = "src/lib/lib.rs"

[package]
name = "blackbody"
description = "Blackbody is an image viewer for thermograms."
version = "2.1.0"
license = "EUPL-1.2"
authors = [ "Arthur Nieuwland <anieuwland@nimmerfort.eu>",]
edition = "2021"
repository = "https://bitbucket.org/nimmerwoner/blackbody/"
